/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceIdRouteImport } from './routes/device.$id'
import { Route as DeviceIdCameraRouteImport } from './routes/device.$id_.camera'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIdRoute = DeviceIdRouteImport.update({
  id: '/device/$id',
  path: '/device/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIdCameraRoute = DeviceIdCameraRouteImport.update({
  id: '/device/$id_/camera',
  path: '/device/$id/camera',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
  '/device/$id': typeof DeviceIdRoute
  '/device/$id/camera': typeof DeviceIdCameraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
  '/device/$id': typeof DeviceIdRoute
  '/device/$id/camera': typeof DeviceIdCameraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
  '/device/$id': typeof DeviceIdRoute
  '/device/$id_/camera': typeof DeviceIdCameraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/transfer'
    | '/device/$id'
    | '/device/$id/camera'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/transfer' | '/device/$id' | '/device/$id/camera'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/transfer'
    | '/device/$id'
    | '/device/$id_/camera'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TransferRoute: typeof TransferRoute
  DeviceIdRoute: typeof DeviceIdRoute
  DeviceIdCameraRoute: typeof DeviceIdCameraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$id': {
      id: '/device/$id'
      path: '/device/$id'
      fullPath: '/device/$id'
      preLoaderRoute: typeof DeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$id_/camera': {
      id: '/device/$id_/camera'
      path: '/device/$id/camera'
      fullPath: '/device/$id/camera'
      preLoaderRoute: typeof DeviceIdCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TransferRoute: TransferRoute,
  DeviceIdRoute: DeviceIdRoute,
  DeviceIdCameraRoute: DeviceIdCameraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
